parameters:
     amazon_s3_client.class: Angle\Common\S3Bundle\Services\AmazonS3Client

services:
     amazon_s3_client:
         class:     %amazon_s3_client.class%
         arguments: [%amazon_s3_key%, %amazon_s3_secret%, %amazon_s3_bucket%, %amazon_s3_region%]

     twig.twig_extension.s3Url:
         class: Angle\Common\S3Bundle\Twig\AmazonS3UrlTwigExtension
         public: false
         arguments: [ "@=container.hasParameter('cdn_prefix_url') ? parameter('cdn_prefix_url') : ''" ]
         tags:
             - { name: twig.extension }
