parameters:
     amazon_s3.class: Angle\Common\S3Bundle\Services\AmazonS3


services:
     amazon_s3:
         class:     %amazon_s3.class%
         arguments: [%amazon_s3_key%, %amazon_s3_secret%, %amazon_s3_bucket%]
