parameters:
     amazon_s3_client.class: Angle\Common\S3Bundle\Services\AmazonS3Client

services:
     amazon_s3_client:
         class:     %amazon_s3_client.class%
         arguments: [%amazon_s3_key%, %amazon_s3_secret%, %amazon_s3_bucket%]

     twig.twig_extension.s3Url:
             class: Angle\Common\S3Bundle\Twig\AmazonS3UrlExtension
             public: false
             arguments:
                 - { bucket_url: %cdn_prefix_url% }
             tags:
                 - { name: twig.extension }
